# Generated by Django 5.1.7 on 2025-03-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="task_completed",
        ),
    ]
